version: '3.8'
services:
  flask_app:
    image: nolanwyl/flask_app:latest
    ports:
      - "4321:1234"
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
