version: '3.8'

services:
  flask_app:
    image: nolanwyl/flask_app:latest
    container_name: kubeflow-flask_app-1
    ports:
      - "4321:5000"
    environment:
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: kubeflow-mongo-1
    ports:
      - "27017:27017"
    volumes:
      - data:/db

volumes:
  data:
